# Generated by Django 2.0 on 2018-08-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='dailyRentalRate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='numberInStock',
            field=models.IntegerField(),
        ),
    ]
